### ISSUE TITLE
Problem runing example docker-compose

### ISSUE THREAD

**Issue by matjazmav** [jwilder/nginx-proxy#1063]
It is probably something with socket, but couldn't found solution.

**docker-compose.yml**
```
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
```

**$ docker version**
```
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true
```

**$ docker-compose up**
```
Pulling nginx-proxy (jwilder/nginx-proxy:latest)...
latest: PTraceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\main.py", line 959, in up
  File "compose\project.py", line 452, in up
  File "compose\service.py", line 318, in ensure_image_exists
  File "compose\service.py", line 1081, in pull
  File "compose\progress_stream.py", line 23, in stream_output
  File "compose\progress_stream.py", line 92, in print_output_event
  File "codecs.py", line 370, in write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
IOError: [Errno 0] Error
Failed to execute script docker-compose
```

**Comment by kylegoetz** [comment]
shot in the dark here, which version of docker-compose do you have (`docker-compose --version`)? Somehow I ended up with version 1.2 despite having docker v18 on OSX. I manually deleted docker-compose and updated Docker, triggering a re-install of docker-compose, which was a newer version
