### ISSUE TITLE
Cannot start with docker-compose

### ISSUE THREAD

**Issue by julienvincent** [jwilder/nginx-proxy#213]
I am trying to run this proxy via composer, but when I pull and attempt to run it I get a concatenate error.

```
Pulling proxy (jwilder/nginx-proxy:latest)...
latest: Pulling from jwilder/nginx-proxy
81ed27cd249d: Pull complete
df9eb78b1216: Pull complete
67ac1dd29000: Pull complete
7f3c44753d96: Pull complete
b1fc8805e642: Pull complete
eea1541692cf: Pull complete
ec62062b5525: Pull complete
70189116bd8c: Pull complete
98f9ffa0b408: Pull complete
a03af6ef559a: Pull complete
43572229464c: Already exists
   32 B/32 BB Already exists
9a61b6b1315e: Already exists
aface2a79f55: Already exists
5dd2638d10a1: Already exists
97df1ddba09e: Already exists
438d75921414: Already exists
7340fb61bdef: Already exists
51ed40dd3671: Already exists
2b12d66de277: Already exists
4b1798a9cafa: Already exists
61f2d0dc0350: Already exists
ce293cb4a3c9: Already exists
Digest: sha256:c7d46e255e541cc86036dd5f94b1c7da5386d46f22ce3a1f387ccfd2025a5319
Status: Downloaded newer image for jwilder/nginx-proxy:latest
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 32, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 34, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 66, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 471, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 245, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 318, in execute_convergence_plan
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 219, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 552, in _get_container_create_options
TypeError: cannot concatenate 'str' and 'list' objects
```

**Comment by jwilder** [comment]
Appears to be an issue with compose.  This project doesn't use compose or python.  I'd suggest opening an issue there.
